version: '3.8'

services:
  postgresql:
    image: postgres:13-alpine
    container_name: salecar_postgresql
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=salecar
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - salecar_network

  mysql:
    image: mysql:latest
    container_name: salecar_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=salecar
    networks:
      - salecar_network

networks:
  salecar_network:
    driver: bridge